---
stages:
  - lint

lint check:
    image: python:3.6
    stage: lint
    script:
      - pip install pep8 --quiet
      - pep8 --ignore 'E501,C0301,W0142,W0402,R0201,E1101,E1102,C0103,R0901,R0903,R0904,C1001,W0223,W0232,W0201,E1103,R0801,C0111' --statistics .
      - python setup.py check
      - python setup.py test
    tags:
      - python-lint-ext
